version: '3.3'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    ports:
      # Plex DLNA Server
#      - 32400:32400/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    labels:
#      - plex
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.escher.cc`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=default"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.frontend.rule=Host:traefik.domain"
      - "traefik.http.routers.plex.middlewares=middlewares-rate-limit@file,middlewares-ipwhilelist@file" 
    networks:
      - traefik_proxy
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - UMASK=022 #optional
      - PLEX_CLAIM=claim-7Ga1sAii39mutnCYsBHg
      - ADVERTISE_IP=https://plex.escher.cc:443
    restart: unless-stopped
    volumes:
      - cifs-plex:/config
      - cifs-movies:/movies:ro
      - cifs-tv:/tv:ro

volumes:
  cifs-plex:
    external: true
  cifs-movies:
    external: true
  cifs-tv:
    external: true

networks:
  traefik_proxy:
    external: true
