services:
  framadate-db:
    image: mariadb:10.8
    container_name: framadate-DB
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/framadate/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_INITDB_SKIP_TZINFO=1  # Behebt die bekannten Startprobleme

  framadate:
    image: lefilament/framadate
    container_name: framadate
    restart: unless-stopped
    volumes:
      - ./config.php:/var/www/framadate/app/inc/config.php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.framadate.entrypoints=websecure"
      - "traefik.http.routers.framadate.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.framadate.tls=true"
      - "traefik.http.routers.framadate.tls.certresolver=default"
      - "traefik.http.routers.framadate.middlewares=secHeaders@file"
      - "traefik.http.services.framadate.loadbalancer.server.port=80"
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASS}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_HOST=framadate-db
      - MYSQL_PORT=3306
      - DOMAIN=${DOMAIN}
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external: true
