version: '3.3'

services:
  nc-redis:
    image: redis:alpine
    container_name: nc-redis
    hostname: nc-redis
    networks:
      - traefik_proxy
      - db-net
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nc-app:
    image: nextcloud
    entrypoint: sh -c "apt update && apt install -y nano libmagickcore-6.q16-6-extra && /entrypoint.sh apache2-foreground"
    container_name: nc-app
    restart: unless-stopped
    depends_on:
      - nc-redis
    environment:
      - MYSQL_HOST=aio-sql:3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1  # Behebt die bekannten Startprobleme der Datenbank
      - REDIS_HOST=nc-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEPROTOCOL=https
#     - OVERWRITECLIURL=https://${NEXTCLOUD_URL}
#     - MYSQL_DATABASE=${MYSQL_DATABASE}
#     - MYSQL_USER=${MYSQL_USER}
#     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#     - MYSQL_HOST=nc-db
#     - NEXTCLOUD_ADMIN_USER=admin
#     - NEXTCLOUD_ADMIN_PASSWORD=nextcloud-pass

volumes:
      - /mnt/array/nextcloud:/var/www/html   
      - ./nextcloud-apache.conf:/etc/apache2/conf-enabled/nextcloud-apache.conf:ro
      # - EXTERNES DATENVERZEICHNIS:/mnt/array/nextcloud
#    links:
#      - aio-sql
#    external_links:
#      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_URL}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=default"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,secHeaders@file"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
    networks:
      - traefik_proxy
      - db-net

  nc-cron:
    image: nextcloud
    container_name: nc-cron
    restart: unless-stopped
    volumes:
      - /var/docker/nextcloud/app:/var/www/html
      # - EXTERNES DATENVERZEICHNIS:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nc-redis
    networks:
      - traefik_proxy
      - db-net

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  db-net:
    external:
      name: db-net
