services:
  nextcloud-db:
    image: mariadb:10.8
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1  # Behebt die bekannten Startprobleme der Datenbank

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    networks:
      - default
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nextcloud-app:
    image: nextcloud
    entrypoint: sh -c "apt update && apt install -y nano smbclient libmagickcore-6.q16-6-extra && /entrypoint.sh apache2-foreground"
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEPROTOCOL=https
      - PHP_MEMORY_LIMIT=51200M
      - PHP_UPLOAD_LIMIT=51200M
#     - OVERWRITECLIURL=https://${NEXTCLOUD_URL}
#     - MYSQL_DATABASE=${MYSQL_DATABASE}
#     - MYSQL_USER=${MYSQL_USER}
#     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#     - MYSQL_HOST=nc-db
#     - NEXTCLOUD_ADMIN_USER=admin
#     - NEXTCLOUD_ADMIN_PASSWORD=nextcloud-pass
      
    volumes:
      - /var/docker/nextcloud/app:/var/www/html
      - ./nextcloud-apache.conf:/etc/apache2/conf-enabled/nextcloud-apache.conf:ro
      # - EXTERNES DATENVERZEICHNIS:/var/www/html/data
    links:
      - nextcloud-db
#    external_links:
#      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_URL}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=default"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,secHeaders@file"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/(?:card|cal)dav'"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
    networks:
      - traefik_proxy
      - default

  nextcloud-cron:
    image: nextcloud
    restart: unless-stopped
    volumes:
      - /var/docker/nextcloud/app:/var/www/html
      # - EXTERNES DATENVERZEICHNIS:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis

volumes:
  redis:

networks:
  traefik_proxy:
    external: true
  default:
    driver: bridge
