version: '3.3'
services:
  collabora:
    image: collabora/code
    container_name: collabora_app
    networks:
      - traefik_proxy
    cap_add:
      - MKNOD
    expose:
      - 9980
    environment:
      - domain=${NEXTCLOUD_DOMAIN}
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:net.proto=IPv4"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora-secure.entrypoints=websecure"
      - "traefik.http.routers.collabora-secure.rule=Host(`${COLLABORA_DOMAIN}`)"
      - "traefik.http.routers.collabora-secure.tls=true"
      - "traefik.http.routers.collabora-secure.tls.certresolver=default"
      - "traefik.http.routers.collabora-secure.service=collabora"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.collabora-secure.middlewares=secHeaders@file"
networks:
  traefik_proxy:
    external: true
  default:
    driver: bridge
