version: '3'

services:
  osticket:
    image: devinsolutions/osticket
    container_name: osticket
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.osticket.entrypoints=websecure"
      - "traefik.http.routers.osticket.rule=Host(`${OSTICKET_DOMAIN}`)"
      - "traefik.http.routers.osticket.tls=true"
      - "traefik.http.routers.osticket.tls.certresolver=default"
      - "traefik.http.routers.osticket.middlewares=secHeaders@file"
      - "traefik.http.services.osticket.loadbalancer.server.port=80"
    environment:
      - INSTALL_NAME=${INSTALL_NAME}
      - ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${ADMIN_LASTNAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - INSTALL_URL=${INSTALL_URL}
    networks:
      - traefik_proxy
      - db-net

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  db-net:
    external:
      name: db-net
