services:

  ffsync:
    image: "crazymax/firefox-syncserver:latest"
    container_name: "ffsync"
    restart: unless-stopped
    volumes:
      - "ffsync:/data"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - TZ=Europe/Berlin
      - FF_SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - FF_SYNCSERVER_FORWARDED_ALLOW_IPS=*
      - FF_SYNCSERVER_PUBLIC_URL=${FF_SYNC_DOMAIN}
      - FF_SYNCSERVER_SECRET=${FF_SECRET_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ffsync.rule=Host(`${FF_SYNC_DOMAIN}`)"
      - "traefik.http.routers.ffsync.tls=true"
      - "traefik.http.routers.ffsync.entrypoints=websecure"
      - "traefik.http.routers.ffsync.tls.certresolver=default"
      - "traefik.http.services.ffsync.loadbalancer.server.port=5000"
    networks:
      - traefik_proxy

volumes:
  ffsync:
    external: true

networks:
  traefik_proxy:
    external: true
