version: "3.9"

services:
    web:
        image: nginx:latest
#        ports:
#            - "8088:80"
        volumes:
            - ./app:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.vaultwarden.entrypoints=websecure"
          - "traefik.http.routers.vaultwarden.rule=Host(`mail.escher.cc`)"
          - "traefik.http.routers.vaultwarden.tls=true"
          - "traefik.http.routers.vaultwarden.tls.certresolver=default"
          - "traefik.http.routers.vaultwarden.middlewares=secHeaders@file"
          - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
        networks:
          - traefik_proxy

    php-fpm:
      build: .
      user: "${UID_GID}"
      volumes:
          - ./app:/var/www/html
          - ./php.ini:/usr/local/etc/php/php.ini

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
