---
version: '3.3'

services:
  wordpress:
    image: wordpress:6
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
#      - /var/docker/wordpress/data:/var/www/html/wp-content
      - wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=aio-sql:3306
      - WORDPRESS_DB_USER=*****
      - WORDPRESS_DB_PASSWORD=*****
      - WORDPRESS_DB_NAME=*****
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.rule=Host(`www.domain.tld`)"  # Domain anpassen
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=default"
      - "traefik.http.routers.wordpress.middlewares=secHeaders@file"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - db-net

volumes:
  wordpress:
    external: true

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  db-net:
    external:
      name: db-net
