version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htdocs:/htdocs:ro
    ports:
      - 127.0.0.1:80:80/tcp

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paste.entrypoints=websecure"
      - "traefik.http.routers.paste.rule=Host(`paste.lab-tom.de`)"
      - "traefik.http.routers.paste.tls=true"
      - "traefik.http.routers.paste.tls.certresolver=default"
      - "traefik.http.routers.paste.middlewares=secHeaders@file"
      - "traefik.http.services.paste.loadbalancer.server.port=80"
    networks:
      - traefik_proxy

   php:
    image: stikked-php:1
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./htdocs:/htdocs
      - ./docker/stikked.php:/htdocs/application/config/stikked.php:ro
    build:
      context: ./docker/php
    networks:
      - traefik_proxy

  mysql:
    image: mariadb:10.4
    command: mysqld --innodb-buffer-pool-size=4000000000
    volumes:
      - ./mysql-datadir_customize-in-docker-compose.yml:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stikked
      MYSQL_USER: stikked
      MYSQL_PASSWORD: stikked
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
